name: Build CheckerOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, arm]
        exclude:
          - os: windows-latest
            arch: arm 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler on Linux/macOS
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ || brew install gcc

    - name: Set up C++ compiler on Windows
      if: runner.os == 'Windows'
      uses: actions/setup-dotnet@v1

    - name: Build
      run: |
        make

    - name: Run tests
      run: |
        cd build
        ./CheckerOS
