name: Build CheckerOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, arm]
        exclude:
          - os: windows-latest
            arch: arm 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-cpp@v1
      with:
        compiler: g++

    - name: Build
      run: |
        make


    - name: Run tests
      run: |
        cd build
        ./CheckerOS
