name: Build CheckerOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, arm]
        exclude:
          - os: windows-latest
            arch: arm 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Set up C++ compiler on macOS
      if: runner.os == 'macOS'
      run: |
        brew install gcc

    - name: Set up C++ compiler on Windows
      if: runner.os == 'Windows'
      uses: actions/setup-dotnet@v1

    - name: Build
      run: |
        make

    - name: Run test program
      run: |
        cd build
        ./CheckerOS


  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: CheckerOS-${{ matrix.os }}-${{ matrix.arch }}
        path: build/


  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: Deploy to Server
      if: success()
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "build/CheckerOS"
        target: "/home/${{ secrets.SERVER_USERNAME }}/deploy/CheckerOS"